name: CI
on:
    push:
    branches: [ main ]
    pull_request:
    branches: [ main ]
    workflow_dispatch:
jobs:
    acrn_clang_tidy_job:
        runs-on: ubuntu-latest
        name: scan
        steps:
            run:
                - echo "start to check coding guideline violations ..."
        
    checkpatch_job:
        runs-on: ubuntu-latest
        name: scan
        steps:
            run:
                - echo "start to check code styles and typos ..."
                       
    build_job:
        runs-on: ubuntu-latest
        name: build
        uses: actions/upload-artifact@v2
        steps:
            run:
                - echo "start to build ..."
            needs:
                - acrn_clang_tidy_job
            with:
                path:
                - hypervisor/build/
                expire_in: 3 weeks
       
    test_launch_cl_zephyr_job:
        runs-on: ubuntu-latest
        name: test
            run:        
                - echo "start to test lauching clearlinux and zehpyr ..."
            needs:
                - build_job
            only:
                - merge_requests


    
