name: CI
on:
    push:
    branches: [ main ]
    pull_request:
    branches: [ main ]
    workflow_dispatch:
jobs:
    acrn_clang_tidy_job:
        runs-on: ubuntu-latest
        name: scan_1
        steps:
            run:
                - echo "start to check coding guideline violations ..."
                - pwd
                - cd hypervisor
                - make codescan
        only:
            - merge_requests
        
    checkpatch_job:
        runs-on: ubuntu-latest
        name: scan_2
        steps:
            run:
                - echo "start to check code styles and typos ..."
                - pwd
                - git rev-list `git merge-base HEAD origin/master`..HEAD | xargs -n 1 checkpatch.pl --notree --codespell -g
            only:
                - merge_requests
                       
    build_job:
        runs-on: ubuntu-latest
        name: build
        uses: actions/upload-artifact@v2
        steps:
            run:
                - echo "start to build ..."
                - pwd
                - python3 /opt/modify_bootargs.py acrn-sliced-mainline
                - cd hypervisor
                - make clean
                - /opt/acrn-ebtool/docker_run.sh ubuntu:v2.0 "make RELEASE=0"
                - if [ $? -ne 0 ]; then exit 1; fi
            needs:
                - acrn_clang_tidy_job
            with:
                path:
                - hypervisor/build/
                expire_in: 3 weeks
            only:
                - merge_requests
                - schedules
       
    test_launch_cl_zephyr_job:
        runs-on: ubuntu-latest
        name: test
        steps:
            run:        
                - echo "start to test lauching clearlinux and zehpyr ..."
                - pwd
                - /opt/fusa_ci.sh launch_2_vms
            needs:
                - build_job
            only:
                - merge_requests


    
