# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  acrn_clang_tidy_job:
    # The type of runner that the job will run on
    runs-on: self-hosted
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
       - uses: actions/checkout@v2

      # Runs a single command using the runners shell
       - name: Run scan
         run: | 
           export
           echo "--------------------------------------------------"
           echo "start to check code styles and typos ..."
           pwd
           cd hypervisor
           make codescan
      # Runs a set of commands using the runners shell
  #checkpatch_job:
   # steps:
    #  - uses: actions/checkout@v2
   #   - name: Run scan2
   #     run: |
    #       echo "start to check code styles and typos ..."
    #       pwd
       #    git rev-list `git merge-base HEAD origin/master`..HEAD | xargs -n 1 checkpatch.pl --notree --codespell -g
  build_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
            echo "start to build ..."
            pwd
            python3 /opt/modify_bootargs.py acrn-sliced-mainline
            cd hypervisor
            make clean
            /opt/acrn-ebtool/docker_run.sh ubuntu:v2.0 "make RELEASE=0"
            if [ $? -ne 0 ]; then exit 1; fi         

    needs:
            acrn_clang_tidy_job 
        
