# This is a basic workflow to help you get started with Actions

name: CI_v3

# Controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job#1
  acrn_clang_tidy_job:
    runs-on: self-hosted
    steps:
       - uses: actions/checkout@v2
         with:
           fetch-depth: 0
       - name: Run scan
         run: |
           echo "start to check code styles and typos ..."
           cd hypervisor
           make codescan
  # Job#2
#   checkpatch_job:
#     runs-on: self-hosted
#     steps:
#       - name: Run scan2
#         run: |
#           echo "start to check code styles and typos ..."
#           pwd
#           git status
#           git rev-list `git merge-base HEAD origin/main` | xargs -n 1 checkpatch.pl --notree --codespell -g
  # Job#3
  build_job:
    runs-on: self-hosted
    steps:
      - name: build
        run: |
          echo "start to build ..."
          pwd
          python3 /opt/actions/modify_bootargs.py first
          cd hypervisor
          make clean
          /opt/actions/acrn-ebtool/docker_run.sh ubuntu:v2.0 "make RELEASE=0"
          if [ $? -ne 0 ]; then exit 1; fi
    needs:
      acrn_clang_tidy_job
